/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Kalango's
 */
public class TelaPrincipal extends javax.swing.JFrame {

    
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        telaInterna = new javax.swing.JPanel();
        jblData = new javax.swing.JLabel();
        jblHora = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuPedidos = new javax.swing.JMenu();
        menuNovoPedido = new javax.swing.JMenuItem();
        menuUsuarios = new javax.swing.JMenu();
        menuNovoUsuario = new javax.swing.JMenuItem();
        menuBuscarUsuario = new javax.swing.JMenuItem();
        menuAlterarUsuario = new javax.swing.JMenuItem();
        menuExcluirUsuario = new javax.swing.JMenuItem();
        menuProdutos = new javax.swing.JMenu();
        menuNovoProduto = new javax.swing.JMenuItem();
        menuBuscarProduto = new javax.swing.JMenuItem();
        menuAlterarProduto = new javax.swing.JMenuItem();
        menuExcluirProduto = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        menuLogout = new javax.swing.JMenuItem();
        menuSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        javax.swing.GroupLayout telaInternaLayout = new javax.swing.GroupLayout(telaInterna);
        telaInterna.setLayout(telaInternaLayout);
        telaInternaLayout.setHorizontalGroup(
            telaInternaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 727, Short.MAX_VALUE)
        );
        telaInternaLayout.setVerticalGroup(
            telaInternaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 535, Short.MAX_VALUE)
        );

        jblData.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        jblHora.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        menuPedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fast-food64.png"))); // NOI18N
        menuPedidos.setText("Pedidos");
        menuPedidos.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N

        menuNovoPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/order-food.png"))); // NOI18N
        menuNovoPedido.setText("Novo Pedido");
        menuNovoPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNovoPedidoActionPerformed(evt);
            }
        });
        menuPedidos.add(menuNovoPedido);

        jMenuBar1.add(menuPedidos);

        menuUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/businessman.png"))); // NOI18N
        menuUsuarios.setText("Usuários");
        menuUsuarios.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N

        menuNovoUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/add-user.png"))); // NOI18N
        menuNovoUsuario.setText("Novo Usuário");
        menuNovoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNovoUsuarioActionPerformed(evt);
            }
        });
        menuUsuarios.add(menuNovoUsuario);

        menuBuscarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/search user.png"))); // NOI18N
        menuBuscarUsuario.setText("Buscar Usuário");
        menuBuscarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBuscarUsuarioActionPerformed(evt);
            }
        });
        menuUsuarios.add(menuBuscarUsuario);

        menuAlterarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/reload.png"))); // NOI18N
        menuAlterarUsuario.setText("Alterar Usuário");
        menuAlterarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAlterarUsuarioActionPerformed(evt);
            }
        });
        menuUsuarios.add(menuAlterarUsuario);

        menuExcluirUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/remove-user.png"))); // NOI18N
        menuExcluirUsuario.setText("Excluir Usuário");
        menuExcluirUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExcluirUsuarioActionPerformed(evt);
            }
        });
        menuUsuarios.add(menuExcluirUsuario);

        jMenuBar1.add(menuUsuarios);

        menuProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/list64.png"))); // NOI18N
        menuProdutos.setText("Produtos");
        menuProdutos.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N

        menuNovoProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/file.png"))); // NOI18N
        menuNovoProduto.setText("Novo Produto");
        menuNovoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNovoProdutoActionPerformed(evt);
            }
        });
        menuProdutos.add(menuNovoProduto);

        menuBuscarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/search.png"))); // NOI18N
        menuBuscarProduto.setText("Buscar Produto");
        menuBuscarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBuscarProdutoActionPerformed(evt);
            }
        });
        menuProdutos.add(menuBuscarProduto);

        menuAlterarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/refresh.png"))); // NOI18N
        menuAlterarProduto.setText("Alterar Produto");
        menuAlterarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAlterarProdutoActionPerformed(evt);
            }
        });
        menuProdutos.add(menuAlterarProduto);

        menuExcluirProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/file (2).png"))); // NOI18N
        menuExcluirProduto.setText("Excluir");
        menuExcluirProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExcluirProdutoActionPerformed(evt);
            }
        });
        menuProdutos.add(menuExcluirProduto);

        jMenuBar1.add(menuProdutos);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconeSairSistema.png"))); // NOI18N
        jMenu1.setText("Sair");
        jMenu1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N

        menuLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/refresh.png"))); // NOI18N
        menuLogout.setText("Trocar Usuário");
        menuLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLogoutActionPerformed(evt);
            }
        });
        jMenu1.add(menuLogout);

        menuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconeSair.png"))); // NOI18N
        menuSair.setText("Sair do Sistema");
        menuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSairActionPerformed(evt);
            }
        });
        jMenu1.add(menuSair);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jblData, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jblHora, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
            .addGroup(layout.createSequentialGroup()
                .addComponent(telaInterna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(telaInterna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jblData, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jblHora, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(589, 589, 589))
        );

        setSize(new java.awt.Dimension(705, 607));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuNovoPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNovoPedidoActionPerformed
        // TODO add your handling code here:
        telaInterna.removeAll();
        Dimension resolucao = telaInterna.getSize();
        TelaPedidos pedido = new TelaPedidos();
        pedido.getSize(resolucao);
        telaInterna.add(pedido);
        pedido.setLocation(0,0);
        pedido.setVisible(true);
    }//GEN-LAST:event_menuNovoPedidoActionPerformed

    private void menuAlterarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAlterarUsuarioActionPerformed
        // TODO add your handling code here:
        telaInterna.removeAll();
        Dimension resolucao = telaInterna.getSize();
        TelaUsuarioAlterar alterar = new TelaUsuarioAlterar();
        alterar.getSize(resolucao);
        telaInterna.add(alterar);
        alterar.setLocation(0,0);
        alterar.setVisible(true);
        
    }//GEN-LAST:event_menuAlterarUsuarioActionPerformed

    private void menuAlterarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAlterarProdutoActionPerformed
        // TODO add your handling code here:
        telaInterna.removeAll();
        Dimension resolucao = telaInterna.getSize();
        TelaProdutoAlterar alterar = new TelaProdutoAlterar();
        alterar.getSize(resolucao);
        telaInterna.add(alterar);
        alterar.setLocation(0,0);
        alterar.setVisible(true);
    }//GEN-LAST:event_menuAlterarProdutoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
        Date dataSistema = new Date();
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        jblData.setText(formato.format(dataSistema));
        
        //hora
        Timer timer = new Timer(1000, new hora());
        timer.start();
    }//GEN-LAST:event_formWindowOpened

    private void menuNovoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNovoUsuarioActionPerformed
        // TODO add your handling code here:
        telaInterna.removeAll();
        Dimension resolucao = telaInterna.getSize();
        TelaUsuario novo = new TelaUsuario();
        novo.setSize(resolucao);
        telaInterna.add(novo);
        novo.setLocation(0,0);
        novo.setVisible(true);
        
    }//GEN-LAST:event_menuNovoUsuarioActionPerformed

    private void menuBuscarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBuscarUsuarioActionPerformed
        // TODO add your handling code here:
        telaInterna.removeAll();
        Dimension resolucao = telaInterna.getSize();
        TelaUsuarioBuscar buscar = new TelaUsuarioBuscar();
        buscar.setSize(resolucao);
        telaInterna.add(buscar);
        buscar.setLocation(0,0);
        buscar.setVisible(true);
        
    }//GEN-LAST:event_menuBuscarUsuarioActionPerformed

    private void menuExcluirUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExcluirUsuarioActionPerformed
        // TODO add your handling code here:
        telaInterna.removeAll();
        Dimension resolucao = telaInterna.getSize();
        TelaUsuarioExcluir excluir = new TelaUsuarioExcluir();
        excluir.setSize(resolucao);
        telaInterna.add(excluir);
        excluir.setLocation(0,0);
        excluir.setVisible(true);
        
    }//GEN-LAST:event_menuExcluirUsuarioActionPerformed

    private void menuNovoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNovoProdutoActionPerformed
        // TODO add your handling code here:
        telaInterna.removeAll();
        Dimension resolucao = telaInterna.getSize();
        TelaProduto novo = new TelaProduto();
        novo.setSize(resolucao);
        telaInterna.add(novo);
        novo.setLocation(0,0);
        novo.setVisible(true);
        
    }//GEN-LAST:event_menuNovoProdutoActionPerformed

    private void menuBuscarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBuscarProdutoActionPerformed
        // TODO add your handling code here:
        telaInterna.removeAll();
        Dimension resolucao = telaInterna.getSize();
        TelaProdutoBuscar buscar = new TelaProdutoBuscar();
        buscar.setSize(resolucao);
        telaInterna.add(buscar);
        buscar.setLocation(0,0);
        buscar.setVisible(true);
        
    }//GEN-LAST:event_menuBuscarProdutoActionPerformed

    private void menuExcluirProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExcluirProdutoActionPerformed
        // TODO add your handling code here:
        telaInterna.removeAll();
        Dimension resolucao = telaInterna.getSize();
        TelaProdutoExcluir excluir = new TelaProdutoExcluir();
        excluir.setSize(resolucao);
        telaInterna.add(excluir);
        excluir.setLocation(0,0);
        excluir.setVisible(true);
        
    }//GEN-LAST:event_menuExcluirProdutoActionPerformed

    private void menuLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLogoutActionPerformed
        // TODO add your handling code here:
        TelaLogin login = new TelaLogin();
        JOptionPane.showMessageDialog(null, "Entre com Login e Senha!" );
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_menuLogoutActionPerformed

    private void menuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSairActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Bye! Bye!");
        System.exit(0);
    }//GEN-LAST:event_menuSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel jblData;
    private javax.swing.JLabel jblHora;
    private javax.swing.JMenuItem menuAlterarProduto;
    private javax.swing.JMenuItem menuAlterarUsuario;
    private javax.swing.JMenuItem menuBuscarProduto;
    private javax.swing.JMenuItem menuBuscarUsuario;
    private javax.swing.JMenuItem menuExcluirProduto;
    private javax.swing.JMenuItem menuExcluirUsuario;
    private javax.swing.JMenuItem menuLogout;
    private javax.swing.JMenuItem menuNovoPedido;
    private javax.swing.JMenuItem menuNovoProduto;
    private javax.swing.JMenuItem menuNovoUsuario;
    private javax.swing.JMenu menuPedidos;
    private javax.swing.JMenu menuProdutos;
    private javax.swing.JMenuItem menuSair;
    private javax.swing.JMenu menuUsuarios;
    private javax.swing.JPanel telaInterna;
    // End of variables declaration//GEN-END:variables

class hora implements ActionListener{
        @Override
        public void actionPerformed(ActionEvent e) {
            Calendar now = Calendar.getInstance();
            jblHora.setText(String.format("%1$tH:%1$tM:%1$tS", now));
        }
    }
}
